version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Starting Docker daemon..."
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  pre_build:
    commands:
      - echo "Staging JAR ..."
      - aws s3 cp s3://${APP_BUCKET}/${APP_BUCKET_PREFIX}/${APP_NAME}/${APP_VER}/app/ binaries/ --recursive --include "*"
      - bash -c "[ -n '$DOCKER_HUB_USER' ] &&  docker login -u '$DOCKER_HUB_USER' -p '$DOCKER_HUB_PASSWORD'"

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...      
      - VER="$APP_NAME-$APP_VER-$CODEBUILD_BUILD_NUMBER"
      - LATEST="${APP_NAME}-latest"
      - bash ./docker-retry.sh  build -t $IMAGE_REPO_NAME:$VER .
      - docker tag $IMAGE_REPO_NAME:$VER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$VER
      - docker tag $IMAGE_REPO_NAME:$VER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$LATEST

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$VER
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$LATEST
